// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PM.Gallery.Infrastructure.EntityFrameworkCore;

#nullable disable

namespace PM.Gallery.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PM.Gallery.Domain.Entities.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<byte[]>("ImageData")
                        .IsRequired()
                        .HasColumnType("mediumblob");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("PM.Gallery.Domain.Entities.Image", b =>
                {
                    b.OwnsMany("PM.Gallery.Domain.ValueObjects.Comment", "Comments", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("datetime(6)");

                            b1.Property<Guid>("ImageId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("varchar(1000)");

                            b1.HasKey("Id");

                            b1.HasIndex("ImageId");

                            b1.ToTable("Comments", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ImageId");
                        });

                    b.OwnsMany("PM.Gallery.Domain.ValueObjects.Rating", "Ratings", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("datetime(6)");

                            b1.Property<Guid>("ImageId")
                                .HasColumnType("char(36)");

                            b1.Property<int>("Score")
                                .HasColumnType("int");

                            b1.HasKey("Id");

                            b1.HasIndex("ImageId");

                            b1.ToTable("Ratings", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ImageId");
                        });

                    b.OwnsMany("PM.Gallery.Domain.ValueObjects.Tag", "Tags", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("datetime(6)");

                            b1.Property<Guid>("ImageId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("varchar(30)");

                            b1.HasKey("Id");

                            b1.HasIndex("ImageId");

                            b1.ToTable("Tags", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ImageId");
                        });

                    b.Navigation("Comments");

                    b.Navigation("Ratings");

                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
